# Personal Portfolio Website
This is my personal portfolio website where I showcase my projects, skills, certifications, and experience.  
## ğŸ“Œ Features
- Home section
- Projects section
- Skills section
- Certifications
- personal information
- resume
## ğŸš€ Technologies Used
- HTML
- CSS
## ğŸ‘©â€ğŸ’» Developed By
Himaja Ponnaganti
